#!/usr/bin/env bash

_kill() {
    taskkill /f /im "$1.exe"
}

{
    _kill 'vmware-authd'
    _kill 'vmware-hostd'
    _kill 'vmware-usbarbitrator64'
    _kill 'exim-4.86-1'
    _kill 'microsoft.photos'
    _kill 'deluge'
    _kill 'deluged'
    _kill 'privatetunnel2.7.0'
    _kill 'iastoricon'
    _kill 'applemobiledeviceservice'
    _kill 'winstore.mobile'
    _kill 'xboxapp'
    _kill 'ovpnagent'
    _kill 'softwareupdate'
    _kill 'onenoteim'
    _kill 'microsoft.msn.weather'
    _kill 'video.ui'
    _kill 'music.ui'
    _kill 'onedrive'
    _kill 'time'
    _kill 'gamebarpresencewriter'
    _kill 'peopleapp'
    _kill 'systemsettingsadminflows'
    _kill 'hxtsr'
    _kill 'hxcalendarappimm'
    _kill 'searchindexer'
    _kill 'connectivitystore.windows'
    _kill 'scheduler'
    _kill 'installagent'
    _kill 'microsoft.stickynotes'
    _kill 'tv_x64'
    _kill 'tv_w32'
    _kill 'teamviewer_service'
    _kill 'teamviewer'
    _kill 'pickerhost'
    _kill 'lockapphost'
    _kill 'dismhost'
    _kill 'applicationframehost'
    _kill 'settingsynchost'
    _kill 'shellexperiencehost'
    _kill 'etdctrlhelper'
    _kill 'etdctrl'
    _kill 'etdgesture'
    _kill 'searchui'
} 2>/dev/null
